name: Automated Merge on Test Pass

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pytest
        run: pip install pytest
        
      - name: Run streamlit-Delos_Reyes
        run: pytest streamlit-Delos_Reyes/app.py

      - name: Merge on Success
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: token $GH_TOKEN" -X POST -d '{"base":"main","head":"$GITHUB_REF"}' "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls" | jq -r '.number')
          curl -s -H "Authorization: token $GH_TOKEN" -X PUT "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge"
